tls:
  enabled: false

mqtt:
  host: mosquitto

cameras:
  dummy_camera_1:
    enabled: false
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1/dummy
        roles:
        - detect
    detect:
      width: 1280
      height: 720