name: "Docker Compose Test (Tang)"

on:
  pull_request:
    branches: master
  push:
    branches: master
  schedule:
  - cron: "0 8 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: "Git: Checkout"
        uses: actions/checkout@v2
      -
        name: "Service: Start"
        run: |
          ./service.sh up --no-override tang
      -
        name: "Service: Wait"
        run: |
          sleep 60s
      -
        name: "Service: Test"
        run: |
          cd tang
          REPLY="$(docker inspect --format '{{json .State.Health.Status}}' $(docker-compose ps -q tang))"
          [[ "$REPLY" == '"healthy"' ]] || exit 1
